global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          host: "localhost"
          env: "local"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

# Alerting rules will be added here in Weeks 5-6
# rule_files:
#   - "alert_rules.yml"
