[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name              systemd
    Tag               host.systemd
    DB                /fluent-bit/state/systemd.db
    Read_From_Tail    On

[OUTPUT]
    Name        loki
    Match       host.*
    Host        loki
    Port        3100
    Labels      job=fluent-bit,source=systemd